%离散时间系统的单位脉冲响应
a=[1,-1,0.91];
b=[1];%系统函数，a是分母系数，b是分子系数/在这里更改系统函数
n0=0;
n=-20:120;
x=[(n-n0)==0];%冲击函数
h=filter(b,a,x);%用filter函数滤波
figure(1);
stem(n,h)%离散作图
title('冲激响应');
xlabel('n');
ylabel('h(n)');
figure(2);
[z,p,g]=tf2zp(b,a);%传递函数转化为零极点状态_tf2zp，z为零点，p为极点，k是增益
zplane(z,p);%z域作图